//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBooking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bus()
        {
            this.schedules = new HashSet<schedule>();
        }
       
        [Display(Name = "Bus ID")]
        public int bus_id { get; set; }

        //Validation for bus name and error message if not valid
        [Display(Name = "Bus Name")]
        [StringLength(50, ErrorMessage = "The Bus name must be at least 4 characters long.", MinimumLength = 4)]
        public string bus_name { get; set; }
      
        [Display(Name = "Bus Type")]
        public int bus_type_id { get; set; }

        //Validation for no. of total seats in the buses and error message if not valid
        [Display(Name = "Total Seats")]
        [RegularExpression("^[0-9]{1,10}$", ErrorMessage = "Please Enter numerics")]
        public int total_seats { get; set; }
    
        public virtual buses_type buses_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schedule> schedules { get; set; }
    }
}
