//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBooking
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class creditcard_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public creditcard_type()
        {
            this.transactions = new HashSet<transaction>();
        }
    
        public int c_id { get; set; }

        //Validation for credit card name and error message if not valid
        [Display(Name = "Credit Card Name")]
        [StringLength(50, ErrorMessage = "The must be at least 6 characters long.", MinimumLength =6)]
        [Required(ErrorMessage = "required")]
        public string name { get; set; }

        //Validation for starting two digits of credit  card and error message if not valid
        [Display(Name = "Credit Card Number Starts with")]
        [RegularExpression(@"^\d{2}$", ErrorMessage ="Give only two numbers")]
        public string starts_with { get; set; }

        //Validation for the length of credit card number and error message if not valid
        [Display(Name = "Length")]
        [RegularExpression(@"^\d{2}$", ErrorMessage = "Give only two numbers")]
        public decimal length { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
